events {
    worker_connections 1024;
}

http {
    upstream game_service {
        server game-service:3001;
        # ถ้า scale เป็นหลาย container จะเพิ่ม line ได้ เช่น
        # server game-service-2:3001;
    }

    upstream score_service {
        server score-service:3002;
    }

    upstream frontend {
        server frontend:3000;
    }

    server {
        listen 8080;

        location /api/game/ {
            proxy_pass http://game_service/;
            proxy_set_header Host $host;
        }

        location /api/score/ {
            proxy_pass http://score_service/;
            proxy_set_header Host $host;
        }

        # WebSocket ต้องมี header พิเศษเพิ่ม
        location /socket.io/ {
            proxy_pass http://score_service;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
        }
    }
}